[project]
name = "password-stretcher"
version = "2.0.8"
description = "A deadly password mangler, forked from TheTechromancer"
authors = [{name = "35ABDA637EC99C"}]
license = "GPL-3.0"
requires-python = ">=3.12"

dependencies = ["psutil<=7.2.2"]

[project.urls]
Repository = "https://github.com/35ABDA637EC99C/password-stretcher"

[build-system]
requires = ["setuptools >= 45.2.0"] # Have at least ubuntu 20.04
build-backend = "setuptools.build_meta"

[project.scripts]
password-stretcher = "password_stretcher.stretcher:main"
